# Generated by Django 3.2.6 on 2021-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
